<h2><br> 1. Create a 3x3 matrix array with values ranging from 2 to 10.
<br>2. Create a NumPy array having user input values and convert the integer
type to the float type of the elements of the array. For instance: Original
array [1, 2, 3, 4] Array converted to a float type: [ 1. 2. 3. 4.]
<br>3. Write a NumPy program to append values to the end of an array. For
instance: Original array: [10, 20, 30] . After that, append values to the end
of the array: [10 20 30 40 50 60 70 80 90]
<br>4. Create two NumPy arrays and add the elements of both the arrays and
store the result in sumArray.
<br>5. Create a 3x3 array having values from 10-90 (interval of 10) and store that
in array1
Perform the following tasks:
<br>a. Extract the 1st row from the array
<br>b. Extract the last element from the array
</h2>

In [2]:
import numpy as np

# Create a 3x3 matrix array with values ranging from 2 to 10
matrix = np.arange(2, 11).reshape(3, 3)
print("3x3 Matrix with values from 2 to 10:")
print(matrix)

3x3 Matrix with values from 2 to 10:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [6]:
# Create a NumPy array having user input values and convert the integer type to the float type
user_input = input("Enter numbers separated by spaces: ")
int_array = np.array(list(map(int, user_input.split())))
float_array = int_array.astype(float)
print("Original array:", int_array)
print("Array converted to float type:", float_array)

Enter numbers separated by spaces:  2 5 6 


Original array: [2 5 6]
Array converted to float type: [2. 5. 6.]


In [5]:
# Write a NumPy program to append values to the end of an array
original_array = np.array([10, 20, 30])
values_to_append = np.array([40, 50, 60, 70, 80, 90])
appended_array = np.append(original_array, values_to_append)
print("Original array:", original_array)
print("Array after appending values:", appended_array)

Original array: [10 20 30]
Array after appending values: [10 20 30 40 50 60 70 80 90]


In [4]:
# Create two NumPy arrays and add the elements of both the arrays and store the result in sumArray
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
sumArray = np.add(array1, array2)
print("Array 1:", array1)
print("Array 2:", array2)
print("Sum of both arrays:", sumArray)

Array 1: [1 2 3]
Array 2: [4 5 6]
Sum of both arrays: [5 7 9]


In [3]:
# Create a 3x3 array having values from 10-90 (interval of 10) and store that in array1
array1 = np.arange(10, 100, 10).reshape(3, 3)
print("3x3 Array with values from 10 to 90:")
print(array1)

# a. Extract the 1st row from the array
first_row = array1[0, :]
print("First row of the array:", first_row)

# b. Extract the last element from the array
last_element = array1[-1, -1]
print("Last element of the array:", last_element)

3x3 Array with values from 10 to 90:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
First row of the array: [10 20 30]
Last element of the array: 90
