<h2>
<br>1.Create a function that takes dimensions as tuples e.g. (3, 3) and a numeric value and returns a NumPy array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return [ [5, 5, 5], [5, 5, 5], [5, 5, 5] ]
<br>2.Create a method that takes n NumPy arrays of the same dimensions, sums them and returns the answer.
<br>3. Given a 2 D Array of N X M Dimension, write a function that accepts this array as well as two numbers N and M. The method should return the top-left N X M sub matrix, e.g: [ [1, 2, 3], [4, 5, 6], [7, 8, 9], ] top_left_sub_matrix (matrix, 2, 2) -> should return: [ [1, 2] [4, 5] ]
<br>4. Given a 2 D Array of N X M Dimension, write a function that accepts this array as well as two numbers N and M. The method should return the bottom-right N X M sub matrix, e.g: [ [1, 2, 3], [4, 5, 6], [7, 8, 9], ] sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed) [ [5, 6] [8, 9] ]
<br>5.Given a 1 D NumPy Array. Write a function that accepts this array as parameters. The method should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's standard deviation as values: [1, 1, 1] solution(arr) -> should return : {'mean': 1.0, 'std_dev': 0.0}
</h2>

In [10]:
import numpy as np

def solve(dimensions, value):
    # Create a NumPy array of the given dimensions filled with the given value
    return np.full(dimensions, value)
    
def sum_arrays(*arrays):
    # Sum the given NumPy arrays
    return np.sum(arrays, axis=0)

def top_left_sub_matrix(matrix, N, M):
    # Return the top-left N x M sub matrix
    return matrix[:N, :M]

def bottom_right_sub_matrix(matrix, N, M):
    # Return the bottom-right N x M sub matrix
    return matrix[-N:, -M:]

def solution(arr):
    # Calculate the mean and standard deviation of the array
    mean = np.mean(arr)
    std_dev = np.std(arr)
    return {'mean': mean, 'std_dev': std_dev}


# Example usage
result = solve((3, 3), 5)
print("Task 1 Result:")
print(result)
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
result = sum_arrays(array1, array2)
print("Task 2 Result:")
print(result)
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = top_left_sub_matrix(matrix, 2, 2)
print("Task 3 Result:")
print(result)
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = bottom_right_sub_matrix(matrix, 2, 2)
print("Task 4 Result:")
print(result)
arr = np.array([1, 1, 1])
result = solution(arr)
print("Task 5 Result:")
print(result)

Task 1 Result:
[[5 5 5]
 [5 5 5]
 [5 5 5]]
Task 2 Result:
[[10 10 10]
 [10 10 10]
 [10 10 10]]
Task 3 Result:
[[1 2]
 [4 5]]
Task 4 Result:
[[5 6]
 [8 9]]
Task 5 Result:
{'mean': np.float64(1.0), 'std_dev': np.float64(0.0)}
